/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

import { authMeSchema } from '../authMeSchema'

/** Success */
export const getAuthMe200Schema = z.lazy(() => authMeSchema)

/** Not authenticated */
export const getAuthMe401Schema = z.unknown()

export const getAuthMeQueryResponseSchema = z.lazy(() => getAuthMe200Schema)
