/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

import { typeSchema } from '../typeSchema'

/** Success */
export const getCompletedSkillsByCore200Schema = z.array(
	z.object({
		get core() {
			return typeSchema
		},
		coreName: z.string(),
		skills: z.array(
			z.object({
				id: z.string(),
				title: z.string(),
			}),
		),
	}),
)

/** Not authenticated */
export const getCompletedSkillsByCore401Schema = z.unknown()

export const getCompletedSkillsByCoreQueryResponseSchema = z.lazy(
	() => getCompletedSkillsByCore200Schema,
)
