/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { GetAuthMe200, GetAuthMeQueryResponse } from '../../types/meController/GetAuthMe'

import { faker } from '@faker-js/faker'

import { createAuthMe } from '../createAuthMe'

/** Success */
export function createGetAuthMe200(data?: Partial<GetAuthMe200>): GetAuthMe200 {
	return createAuthMe(data)
}

/** Not authenticated */
export function createGetAuthMe401() {
	return undefined
}

export function createGetAuthMeQueryResponse(
	data?: Partial<GetAuthMeQueryResponse>,
): GetAuthMeQueryResponse {
	return data || faker.helpers.arrayElement<any>([createGetAuthMe200()])
}
