/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
	GetCompletedSkillsByCore200,
	GetCompletedSkillsByCoreQueryResponse,
} from '../../types/meController/GetCompletedSkillsByCore'

import { faker } from '@faker-js/faker'

import { createType } from '../createType'

/** Success */
export function createGetCompletedSkillsByCore200(
	data?: GetCompletedSkillsByCore200,
): GetCompletedSkillsByCore200 {
	return [
		...faker.helpers.multiple(() => ({
			get core() {
				return createType()
			},
			coreName: faker.string.alpha(),
			skills: faker.helpers.multiple(() => ({
				id: faker.string.alpha(),
				title: faker.string.alpha(),
			})),
		})),
		...(data || []),
	]
}

/** Not authenticated */
export function createGetCompletedSkillsByCore401() {
	return undefined
}

export function createGetCompletedSkillsByCoreQueryResponse(
	data?: Partial<GetCompletedSkillsByCoreQueryResponse>,
): GetCompletedSkillsByCoreQueryResponse {
	return data || faker.helpers.arrayElement<any>([createGetCompletedSkillsByCore200()])
}
