/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

export const coreRowSchema = z.object({
	type: z.optional(z.enum(['frontend', 'backend', 'devops', 'design'])),
	name: z.optional(z.string()),
	description: z.optional(z.string()),
	icon: z.optional(z.enum(['code', 'server', 'ship', 'palette'])),
	is_available: z.optional(z.boolean()),
	display_order: z.optional(z.int().check(z.minimum(0))),
})
