/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

export const skillRowSchema = z.object({
	id: z.optional(z.string()),
	title: z.optional(z.string()),
	topic: z.optional(z.string()),
	difficulty: z.optional(z.enum(['easy', 'medium', 'hard'])),
	questions: z.optional(z.array(z.string())),
	questions_count: z.optional(z.int().check(z.minimum(0))),
})
