/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
	GetSkillById200,
	GetSkillByIdPathParams,
	GetSkillByIdQueryResponse,
} from '../../types/skillsController/GetSkillById'

import { faker } from '@faker-js/faker'

import { createSkill } from '../createSkill'

export function createGetSkillByIdPathParams(
	data?: Partial<GetSkillByIdPathParams>,
): GetSkillByIdPathParams {
	return {
		...{ id: faker.string.alpha() },
		...(data || {}),
	}
}

/** Success */
export function createGetSkillById200(data?: Partial<GetSkillById200>): GetSkillById200 {
	return createSkill(data)
}

/** Not found */
export function createGetSkillById404() {
	return undefined
}

export function createGetSkillByIdQueryResponse(
	data?: Partial<GetSkillByIdQueryResponse>,
): GetSkillByIdQueryResponse {
	return data || faker.helpers.arrayElement<any>([createGetSkillById200()])
}
