/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
	GetSkills200,
	GetSkillsQueryParams,
	GetSkillsQueryResponse,
} from '../../types/skillsController/GetSkills'

import { faker } from '@faker-js/faker'

export function createGetSkillsQueryParams(
	data?: Partial<GetSkillsQueryParams>,
): GetSkillsQueryParams {
	return {
		...{
			search: faker.string.alpha(),
			topic: faker.string.alpha(),
			difficulty: faker.helpers.arrayElement<NonNullable<GetSkillsQueryParams>['difficulty']>(
				['easy', 'medium', 'hard'],
			),
			minQuestionsCount: faker.number.int({ min: 0 }),
			maxQuestionsCount: faker.number.int({ min: 0 }),
		},
		...(data || {}),
	}
}

/** Success */
export function createGetSkills200(data?: GetSkills200): GetSkills200 {
	return [
		...faker.helpers.multiple(() => ({
			id: faker.string.alpha(),
			title: faker.string.alpha(),
			questionsCount: faker.number.int({ min: 0 }),
			difficulty: faker.helpers.arrayElement<
				NonNullable<NonNullable<GetSkills200>[number]>['difficulty']
			>(['easy', 'medium', 'hard']),
			topic: faker.string.alpha(),
		})),
		...(data || []),
	]
}

export function createGetSkillsQueryResponse(
	data?: Partial<GetSkillsQueryResponse>,
): GetSkillsQueryResponse {
	return data || faker.helpers.arrayElement<any>([createGetSkills200()])
}
