/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
	SetSkillCompletion200,
	SetSkillCompletionMutationRequest,
	SetSkillCompletionMutationResponse,
	SetSkillCompletionPathParams,
} from '../../types/skillsController/SetSkillCompletion'

import { faker } from '@faker-js/faker'

import { createSkillCompletion } from '../createSkillCompletion'

export function createSetSkillCompletionPathParams(
	data?: Partial<SetSkillCompletionPathParams>,
): SetSkillCompletionPathParams {
	return {
		...{ id: faker.string.alpha() },
		...(data || {}),
	}
}

/** Success */
export function createSetSkillCompletion200(
	data?: Partial<SetSkillCompletion200>,
): SetSkillCompletion200 {
	return createSkillCompletion(data)
}

/** Invalid request body */
export function createSetSkillCompletion400() {
	return undefined
}

/** Not authenticated */
export function createSetSkillCompletion401() {
	return undefined
}

/** Skill not found */
export function createSetSkillCompletion404() {
	return undefined
}

export function createSetSkillCompletionMutationRequest(
	data?: Partial<SetSkillCompletionMutationRequest>,
): SetSkillCompletionMutationRequest {
	return {
		...{ completed: faker.datatype.boolean() },
		...(data || {}),
	}
}

export function createSetSkillCompletionMutationResponse(
	data?: Partial<SetSkillCompletionMutationResponse>,
): SetSkillCompletionMutationResponse {
	return data || faker.helpers.arrayElement<any>([createSetSkillCompletion200()])
}
