/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type { GetAuthMeQueryResponse, GetAuthMe401 } from '../../types/meController/GetAuthMe'

import fetch from '../../../client'
import { getAuthMeQueryResponseSchema } from '../../zod/meController/getAuthMeSchema'

function getGetAuthMeUrl() {
	const res = { method: 'GET', url: `/api/me` as const }
	return res
}

/**
 * @summary Get the current user profile
 * {@link /api/me}
 */
export async function getAuthMe(config: Partial<RequestConfig> & { client?: Client } = {}) {
	const { client: request = fetch, ...requestConfig } = config

	const res = await request<GetAuthMeQueryResponse, ResponseErrorConfig<GetAuthMe401>, unknown>({
		method: 'GET',
		url: getGetAuthMeUrl().url.toString(),
		...requestConfig,
	})
	return getAuthMeQueryResponseSchema.parse(res.data)
}
