/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type {
	GetCompletedSkillsByCoreQueryResponse,
	GetCompletedSkillsByCore401,
} from '../../types/meController/GetCompletedSkillsByCore'

import fetch from '../../../client'
import { getCompletedSkillsByCoreQueryResponseSchema } from '../../zod/meController/getCompletedSkillsByCoreSchema'

function getGetCompletedSkillsByCoreUrl() {
	const res = { method: 'GET', url: `/api/me/completed-skills` as const }
	return res
}

/**
 * @summary Get completed skills grouped by core for the current user
 * {@link /api/me/completed-skills}
 */
export async function getCompletedSkillsByCore(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config

	const res = await request<
		GetCompletedSkillsByCoreQueryResponse,
		ResponseErrorConfig<GetCompletedSkillsByCore401>,
		unknown
	>({ method: 'GET', url: getGetCompletedSkillsByCoreUrl().url.toString(), ...requestConfig })
	return getCompletedSkillsByCoreQueryResponseSchema.parse(res.data)
}
