/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { SkillRow } from '../SkillRow'

export interface GetSkillRowsQueryParams {
	/**
	 * PostgREST filter expression, e.g. "eq.js-closures"
	 *
	 * @type string | undefined
	 */
	id?: string
	/**
	 * PostgREST filter expression, e.g. "ilike._Замыкания_"
	 *
	 * @type string | undefined
	 */
	title?: string
	/**
	 * PostgREST filter expression, e.g. "eq.JavaScript"
	 *
	 * @type string | undefined
	 */
	topic?: string
	/**
	 * PostgREST filter expression, e.g. "eq.medium"
	 *
	 * @type string | undefined
	 */
	difficulty?: string
	/**
	 * One or two PostgREST filter expressions for a range, e.g. "gte.5" and "lte.20"
	 *
	 * @type array | undefined
	 */
	questions_count?: string[]
	/**
	 * PostgREST column projection
	 *
	 * @type string | undefined
	 */
	select?: string
	/** @type string | undefined */
	order?: string
	/**
	 * @type integer | undefined
	 * @minLength 0
	 */
	limit?: number
}

/** Success */
export type GetSkillRows200 = SkillRow[]

export type GetSkillRowsQueryResponse = GetSkillRows200

export type GetSkillRowsQuery = {
	Response: GetSkillRows200
	QueryParams: GetSkillRowsQueryParams
	Errors: any
}
