/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

import { dashboardStatsSchema } from '../dashboardStatsSchema'

/** Success */
export const getDashboardStats200Schema = z.lazy(() => dashboardStatsSchema)

export const getDashboardStatsQueryResponseSchema = z.lazy(() => getDashboardStats200Schema)
