/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type {
	GetExampleQueryResponse,
	GetExample404,
} from '../../types/exampleController/GetExample'

import fetch from '../../../client'
import { getExampleQueryResponseSchema } from '../../zod/exampleController/getExampleSchema'

function getGetExampleUrl() {
	const res = { method: 'GET', url: `/api/example` as const }
	return res
}

/**
 * @summary Example endpoint
 * {@link /api/example}
 */
export async function getExample(config: Partial<RequestConfig> & { client?: Client } = {}) {
	const { client: request = fetch, ...requestConfig } = config

	const res = await request<GetExampleQueryResponse, ResponseErrorConfig<GetExample404>, unknown>(
		{ method: 'GET', url: getGetExampleUrl().url.toString(), ...requestConfig },
	)
	return getExampleQueryResponseSchema.parse(res.data)
}
