/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
	QueryKey,
	QueryClient,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type { GetCoresQueryResponse } from '../../types/coresController/GetCores'

import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

import { getCores } from '../../clients/coresController/getCores'

export const getCoresSuspenseQueryKey = () => [{ url: '/api/cores' }] as const

export type GetCoresSuspenseQueryKey = ReturnType<typeof getCoresSuspenseQueryKey>

export function getCoresSuspenseQueryOptions(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = getCoresSuspenseQueryKey()
	return queryOptions<
		GetCoresQueryResponse,
		ResponseErrorConfig<Error>,
		GetCoresQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return getCores({ ...config, signal: config.signal ?? signal })
		},
	})
}

/**
 * @summary List catalog cores
 * {@link /api/cores}
 */
export function useGetCoresSuspense<
	TData = GetCoresQueryResponse,
	TQueryKey extends QueryKey = GetCoresSuspenseQueryKey,
>(
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				GetCoresQueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient }
		client?: Partial<RequestConfig> & { client?: Client }
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {}
	const { client: queryClient, ...resolvedOptions } = queryConfig
	const queryKey = resolvedOptions?.queryKey ?? getCoresSuspenseQueryKey()

	const query = useSuspenseQuery(
		{
			...getCoresSuspenseQueryOptions(config),
			...resolvedOptions,
			queryKey,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

	query.queryKey = queryKey as TQueryKey

	return query
}
