/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type { GetCoresQueryResponse } from '../../types/coresController/GetCores'

import { queryOptions, useQuery } from '@tanstack/react-query'

import { getCores } from '../../clients/coresController/getCores'

export const getCoresQueryKey = () => [{ url: '/api/cores' }] as const

export type GetCoresQueryKey = ReturnType<typeof getCoresQueryKey>

export function getCoresQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {
	const queryKey = getCoresQueryKey()
	return queryOptions<
		GetCoresQueryResponse,
		ResponseErrorConfig<Error>,
		GetCoresQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return getCores({ ...config, signal: config.signal ?? signal })
		},
	})
}

/**
 * @summary List catalog cores
 * {@link /api/cores}
 */
export function useGetCores<
	TData = GetCoresQueryResponse,
	TQueryData = GetCoresQueryResponse,
	TQueryKey extends QueryKey = GetCoresQueryKey,
>(
	options: {
		query?: Partial<
			QueryObserverOptions<
				GetCoresQueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient }
		client?: Partial<RequestConfig> & { client?: Client }
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {}
	const { client: queryClient, ...resolvedOptions } = queryConfig
	const queryKey = resolvedOptions?.queryKey ?? getCoresQueryKey()

	const query = useQuery(
		{
			...getCoresQueryOptions(config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

	query.queryKey = queryKey as TQueryKey

	return query
}
