/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

export interface CoreRow {
	/** @type string | undefined */
	type?: 'frontend' | 'backend' | 'devops' | 'design'
	/** @type string | undefined */
	name?: string
	/** @type string | undefined */
	description?: string
	/** @type string | undefined */
	icon?: 'code' | 'server' | 'ship' | 'palette'
	/** @type boolean | undefined */
	is_available?: boolean
	/**
	 * @type integer | undefined
	 * @minLength 0
	 */
	display_order?: number
}
