/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

export interface SkillRow {
	/** @type string | undefined */
	id?: string
	/** @type string | undefined */
	title?: string
	/** @type string | undefined */
	topic?: string
	/** @type string | undefined */
	difficulty?: 'easy' | 'medium' | 'hard'
	/** @type array | undefined */
	questions?: string[]
	/**
	 * @type integer | undefined
	 * @minLength 0
	 */
	questions_count?: number
}
