/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

import { coreRowSchema } from '../coreRowSchema'

export const getCoreRowsQueryParamsSchema = z.optional(
	z.object({
		type: z.optional(z.string()),
		select: z.optional(z.string()),
		order: z.optional(z.string()),
		limit: z.optional(z.int().check(z.minimum(0))),
	}),
)

/** Success */
export const getCoreRows200Schema = z.array(z.lazy(() => coreRowSchema))

export const getCoreRowsQueryResponseSchema = z.lazy(() => getCoreRows200Schema)
