/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

/** Success */
export const getExample200Schema = z.object({
	message: z.optional(z.string()),
})

/** Not found */
export const getExample404Schema = z.unknown()

export const getExampleQueryResponseSchema = z.lazy(() => getExample200Schema)
