/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

export const authMeSchema = z.object({
	id: z.string(),
	name: z.string().check(z.minLength(3)),
	email: z.email(),
	gender: z.enum(['male', 'female', 'other']),
	age: z.int().check(z.minimum(1), z.maximum(120)),
	image: z.optional(z.url()),
})
