/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

export const coreSchema = z.object({
	type: z.enum(['frontend', 'backend', 'devops', 'design']),
	name: z.string().check(z.minLength(1)),
	description: z.string().check(z.minLength(1)),
	icon: z.enum(['code', 'server', 'ship', 'palette']),
	isAvailable: z.boolean(),
})
