/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

export const dashboardStatsSchema = z.object({
	skillsCount: z.int().check(z.minimum(0)),
	topicsCount: z.int().check(z.minimum(0)),
	questionsCount: z.int().check(z.minimum(0)),
	completedSkillsCount: z.optional(z.int().check(z.minimum(0))),
})
