/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

export const skillCompletionSchema = z.object({
	completed: z.boolean(),
	completedSkillsCount: z.int().check(z.minimum(0)),
})
