/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
	QueryKey,
	QueryClient,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type {
	GetSkillsQueryResponse,
	GetSkillsQueryParams,
} from '../../types/skillsController/GetSkills'

import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

import { getSkills } from '../../clients/skillsController/getSkills'

export const getSkillsSuspenseQueryKey = (params?: GetSkillsQueryParams) =>
	[{ url: '/api/skills' }, ...(params ? [params] : [])] as const

export type GetSkillsSuspenseQueryKey = ReturnType<typeof getSkillsSuspenseQueryKey>

export function getSkillsSuspenseQueryOptions(
	{ params }: { params?: GetSkillsQueryParams } = {},
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = getSkillsSuspenseQueryKey(params)
	return queryOptions<
		GetSkillsQueryResponse,
		ResponseErrorConfig<Error>,
		GetSkillsQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return getSkills({ params: params }, { ...config, signal: config.signal ?? signal })
		},
	})
}

/**
 * @summary List skill cards
 * {@link /api/skills}
 */
export function useGetSkillsSuspense<
	TData = GetSkillsQueryResponse,
	TQueryKey extends QueryKey = GetSkillsSuspenseQueryKey,
>(
	{ params }: { params?: GetSkillsQueryParams } = {},
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				GetSkillsQueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient }
		client?: Partial<RequestConfig> & { client?: Client }
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {}
	const { client: queryClient, ...resolvedOptions } = queryConfig
	const queryKey = resolvedOptions?.queryKey ?? getSkillsSuspenseQueryKey(params)

	const query = useSuspenseQuery(
		{
			...getSkillsSuspenseQueryOptions({ params }, config),
			...resolvedOptions,
			queryKey,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

	query.queryKey = queryKey as TQueryKey

	return query
}
