/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
	QueryKey,
	QueryClient,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type {
	GetSkillByIdQueryResponse,
	GetSkillByIdPathParams,
	GetSkillById404,
} from '../../types/skillsController/GetSkillById'

import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

import { getSkillById } from '../../clients/skillsController/getSkillById'

export const getSkillByIdSuspenseQueryKey = ({
	id,
}: {
	id: GetSkillByIdPathParams['id'] | undefined
}) => [{ url: '/api/skills/:id', params: { id: id } }] as const

export type GetSkillByIdSuspenseQueryKey = ReturnType<typeof getSkillByIdSuspenseQueryKey>

export function getSkillByIdSuspenseQueryOptions(
	{ id }: { id: GetSkillByIdPathParams['id'] },
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = getSkillByIdSuspenseQueryKey({ id })
	return queryOptions<
		GetSkillByIdQueryResponse,
		ResponseErrorConfig<GetSkillById404>,
		GetSkillByIdQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return getSkillById({ id: id }, { ...config, signal: config.signal ?? signal })
		},
	})
}

/**
 * @summary Get skill by id
 * {@link /api/skills/:id}
 */
export function useGetSkillByIdSuspense<
	TData = GetSkillByIdQueryResponse,
	TQueryKey extends QueryKey = GetSkillByIdSuspenseQueryKey,
>(
	{ id }: { id: GetSkillByIdPathParams['id'] },
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				GetSkillByIdQueryResponse,
				ResponseErrorConfig<GetSkillById404>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient }
		client?: Partial<RequestConfig> & { client?: Client }
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {}
	const { client: queryClient, ...resolvedOptions } = queryConfig
	const queryKey = resolvedOptions?.queryKey ?? getSkillByIdSuspenseQueryKey({ id })

	const query = useSuspenseQuery(
		{
			...getSkillByIdSuspenseQueryOptions({ id }, config),
			...resolvedOptions,
			queryKey,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetSkillById404>> & {
		queryKey: TQueryKey
	}

	query.queryKey = queryKey as TQueryKey

	return query
}
