/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type {
	GetSkillsQueryResponse,
	GetSkillsQueryParams,
} from '../../types/skillsController/GetSkills'

import { queryOptions, useQuery } from '@tanstack/react-query'

import { getSkills } from '../../clients/skillsController/getSkills'

export const getSkillsQueryKey = (params?: GetSkillsQueryParams) =>
	[{ url: '/api/skills' }, ...(params ? [params] : [])] as const

export type GetSkillsQueryKey = ReturnType<typeof getSkillsQueryKey>

export function getSkillsQueryOptions(
	{ params }: { params?: GetSkillsQueryParams } = {},
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = getSkillsQueryKey(params)
	return queryOptions<
		GetSkillsQueryResponse,
		ResponseErrorConfig<Error>,
		GetSkillsQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return getSkills({ params: params }, { ...config, signal: config.signal ?? signal })
		},
	})
}

/**
 * @summary List skill cards
 * {@link /api/skills}
 */
export function useGetSkills<
	TData = GetSkillsQueryResponse,
	TQueryData = GetSkillsQueryResponse,
	TQueryKey extends QueryKey = GetSkillsQueryKey,
>(
	{ params }: { params?: GetSkillsQueryParams } = {},
	options: {
		query?: Partial<
			QueryObserverOptions<
				GetSkillsQueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient }
		client?: Partial<RequestConfig> & { client?: Client }
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {}
	const { client: queryClient, ...resolvedOptions } = queryConfig
	const queryKey = resolvedOptions?.queryKey ?? getSkillsQueryKey(params)

	const query = useQuery(
		{
			...getSkillsQueryOptions({ params }, config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

	query.queryKey = queryKey as TQueryKey

	return query
}
