/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type {
	GetSkillByIdQueryResponse,
	GetSkillByIdPathParams,
	GetSkillById404,
} from '../../types/skillsController/GetSkillById'

import { queryOptions, useQuery } from '@tanstack/react-query'

import { getSkillById } from '../../clients/skillsController/getSkillById'

export const getSkillByIdQueryKey = ({ id }: { id: GetSkillByIdPathParams['id'] | undefined }) =>
	[{ url: '/api/skills/:id', params: { id: id } }] as const

export type GetSkillByIdQueryKey = ReturnType<typeof getSkillByIdQueryKey>

export function getSkillByIdQueryOptions(
	{ id }: { id: GetSkillByIdPathParams['id'] | undefined },
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = getSkillByIdQueryKey({ id })
	return queryOptions<
		GetSkillByIdQueryResponse,
		ResponseErrorConfig<GetSkillById404>,
		GetSkillByIdQueryResponse,
		typeof queryKey
	>({
		enabled: !!id,
		queryKey,
		queryFn: async ({ signal }) => {
			return getSkillById({ id: id! }, { ...config, signal: config.signal ?? signal })
		},
	})
}

/**
 * @summary Get skill by id
 * {@link /api/skills/:id}
 */
export function useGetSkillById<
	TData = GetSkillByIdQueryResponse,
	TQueryData = GetSkillByIdQueryResponse,
	TQueryKey extends QueryKey = GetSkillByIdQueryKey,
>(
	{ id }: { id: GetSkillByIdPathParams['id'] | undefined },
	options: {
		query?: Partial<
			QueryObserverOptions<
				GetSkillByIdQueryResponse,
				ResponseErrorConfig<GetSkillById404>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient }
		client?: Partial<RequestConfig> & { client?: Client }
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {}
	const { client: queryClient, ...resolvedOptions } = queryConfig
	const queryKey = resolvedOptions?.queryKey ?? getSkillByIdQueryKey({ id })

	const query = useQuery(
		{
			...getSkillByIdQueryOptions({ id }, config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<GetSkillById404>> & { queryKey: TQueryKey }

	query.queryKey = queryKey as TQueryKey

	return query
}
