/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type {
	SetSkillCompletionMutationRequest,
	SetSkillCompletionMutationResponse,
	SetSkillCompletionPathParams,
	SetSkillCompletion400,
	SetSkillCompletion401,
	SetSkillCompletion404,
} from '../../types/skillsController/SetSkillCompletion'

import { mutationOptions, useMutation } from '@tanstack/react-query'

import { setSkillCompletion } from '../../clients/skillsController/setSkillCompletion'

export const setSkillCompletionMutationKey = () => [{ url: '/api/skills/:id/completion' }] as const

export type SetSkillCompletionMutationKey = ReturnType<typeof setSkillCompletionMutationKey>

export function setSkillCompletionMutationOptions<TContext = unknown>(
	config: Partial<RequestConfig<SetSkillCompletionMutationRequest>> & { client?: Client } = {},
) {
	const mutationKey = setSkillCompletionMutationKey()
	return mutationOptions<
		SetSkillCompletionMutationResponse,
		ResponseErrorConfig<SetSkillCompletion400 | SetSkillCompletion401 | SetSkillCompletion404>,
		{ id: SetSkillCompletionPathParams['id']; data: SetSkillCompletionMutationRequest },
		TContext
	>({
		mutationKey,
		mutationFn: async ({ id, data }) => {
			return setSkillCompletion({ id, data }, config)
		},
	})
}

/**
 * @summary Set skill completion for the current user
 * {@link /api/skills/:id/completion}
 */
export function useSetSkillCompletion<TContext>(
	options: {
		mutation?: UseMutationOptions<
			SetSkillCompletionMutationResponse,
			ResponseErrorConfig<
				SetSkillCompletion400 | SetSkillCompletion401 | SetSkillCompletion404
			>,
			{ id: SetSkillCompletionPathParams['id']; data: SetSkillCompletionMutationRequest },
			TContext
		> & { client?: QueryClient }
		client?: Partial<RequestConfig<SetSkillCompletionMutationRequest>> & { client?: Client }
	} = {},
) {
	const { mutation = {}, client: config = {} } = options ?? {}
	const { client: queryClient, ...mutationOptions } = mutation
	const mutationKey = mutationOptions.mutationKey ?? setSkillCompletionMutationKey()

	const baseOptions = setSkillCompletionMutationOptions(config) as UseMutationOptions<
		SetSkillCompletionMutationResponse,
		ResponseErrorConfig<SetSkillCompletion400 | SetSkillCompletion401 | SetSkillCompletion404>,
		{ id: SetSkillCompletionPathParams['id']; data: SetSkillCompletionMutationRequest },
		TContext
	>

	return useMutation<
		SetSkillCompletionMutationResponse,
		ResponseErrorConfig<SetSkillCompletion400 | SetSkillCompletion401 | SetSkillCompletion404>,
		{ id: SetSkillCompletionPathParams['id']; data: SetSkillCompletionMutationRequest },
		TContext
	>(
		{
			...baseOptions,
			mutationKey,
			...mutationOptions,
		},
		queryClient,
	) as UseMutationResult<
		SetSkillCompletionMutationResponse,
		ResponseErrorConfig<SetSkillCompletion400 | SetSkillCompletion401 | SetSkillCompletion404>,
		{ id: SetSkillCompletionPathParams['id']; data: SetSkillCompletionMutationRequest },
		TContext
	>
}
