/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type { GetDashboardStatsQueryResponse } from '../../types/dashboardController/GetDashboardStats'

import fetch from '../../../client'
import { getDashboardStatsQueryResponseSchema } from '../../zod/dashboardController/getDashboardStatsSchema'

function getGetDashboardStatsUrl() {
	const res = { method: 'GET', url: `/api/dashboard-stats` as const }
	return res
}

/**
 * @summary Get aggregated catalog and personal progress statistics for the home dashboard
 * {@link /api/dashboard-stats}
 */
export async function getDashboardStats(config: Partial<RequestConfig> & { client?: Client } = {}) {
	const { client: request = fetch, ...requestConfig } = config

	const res = await request<GetDashboardStatsQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: 'GET',
		url: getGetDashboardStatsUrl().url.toString(),
		...requestConfig,
	})
	return getDashboardStatsQueryResponseSchema.parse(res.data)
}
