import type { Metadata } from 'next'
import type { ReactNode } from 'react'

import { NuqsAdapter } from 'nuqs/adapters/next/app'

import { AuthProvider } from '#/components/providers/auth-provider'
import { QueryProvider } from '#/components/providers/query-provider'
import { Toaster } from '#/components/toaster'
import { ttFors } from '#/fonts/ttFors'

import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode
}>) {
	return (
		<html lang="en" data-scroll-behavior="smooth" className={ttFors.variable}>
			<body className="flex min-h-full flex-col">
				<NuqsAdapter>
					<QueryProvider>
						<AuthProvider>
							{children}
							<Toaster />
						</AuthProvider>
					</QueryProvider>
				</NuqsAdapter>
			</body>
		</html>
	)
}
