import type { Metadata } from 'next'
import type { ReactNode } from 'react'

import { headers } from 'next/headers'
import { NuqsAdapter } from 'nuqs/adapters/next/app'

import { Layout } from '#/components/layout'
import { AuthProvider } from '#/components/providers/auth-provider'
import { QueryProvider } from '#/components/providers/query-provider'
import { Toaster } from '#/components/toaster'
import { ttFors } from '#/fonts/ttFors'
import { SsrWidthProvider } from '#/hooks/use-ssr-width'
import { getSsrWidthFromUserAgent } from '#/lib/get-ssr-width-from-user-agent'

import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: ReactNode
}>) {
	const requestHeaders = await headers()
	const ssrWidth = getSsrWidthFromUserAgent(requestHeaders.get('user-agent') ?? '')

	return (
		<html lang="en" data-scroll-behavior="smooth" className={ttFors.variable}>
			<body className="v-stack min-h-full">
				<SsrWidthProvider value={ssrWidth}>
					<NuqsAdapter>
						<QueryProvider>
							<AuthProvider>
								<Layout>{children}</Layout>
								<Toaster />
							</AuthProvider>
						</QueryProvider>
					</NuqsAdapter>
				</SsrWidthProvider>
			</body>
		</html>
	)
}
