/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
	QueryKey,
	QueryClient,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type {
	GetCompletedSkillsByCoreQueryResponse,
	GetCompletedSkillsByCore401,
} from '../../types/meController/GetCompletedSkillsByCore'

import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

import { getCompletedSkillsByCore } from '../../clients/meController/getCompletedSkillsByCore'

export const getCompletedSkillsByCoreSuspenseQueryKey = () =>
	[{ url: '/api/me/completed-skills' }] as const

export type GetCompletedSkillsByCoreSuspenseQueryKey = ReturnType<
	typeof getCompletedSkillsByCoreSuspenseQueryKey
>

export function getCompletedSkillsByCoreSuspenseQueryOptions(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = getCompletedSkillsByCoreSuspenseQueryKey()
	return queryOptions<
		GetCompletedSkillsByCoreQueryResponse,
		ResponseErrorConfig<GetCompletedSkillsByCore401>,
		GetCompletedSkillsByCoreQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return getCompletedSkillsByCore({ ...config, signal: config.signal ?? signal })
		},
	})
}

/**
 * @summary Get completed skills grouped by core for the current user
 * {@link /api/me/completed-skills}
 */
export function useGetCompletedSkillsByCoreSuspense<
	TData = GetCompletedSkillsByCoreQueryResponse,
	TQueryKey extends QueryKey = GetCompletedSkillsByCoreSuspenseQueryKey,
>(
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				GetCompletedSkillsByCoreQueryResponse,
				ResponseErrorConfig<GetCompletedSkillsByCore401>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient }
		client?: Partial<RequestConfig> & { client?: Client }
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {}
	const { client: queryClient, ...resolvedOptions } = queryConfig
	const queryKey = resolvedOptions?.queryKey ?? getCompletedSkillsByCoreSuspenseQueryKey()

	const query = useSuspenseQuery(
		{
			...getCompletedSkillsByCoreSuspenseQueryOptions(config),
			...resolvedOptions,
			queryKey,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetCompletedSkillsByCore401>> & {
		queryKey: TQueryKey
	}

	query.queryKey = queryKey as TQueryKey

	return query
}
