/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type {
	GetCompletedSkillsByCoreQueryResponse,
	GetCompletedSkillsByCore401,
} from '../../types/meController/GetCompletedSkillsByCore'

import { queryOptions, useQuery } from '@tanstack/react-query'

import { getCompletedSkillsByCore } from '../../clients/meController/getCompletedSkillsByCore'

export const getCompletedSkillsByCoreQueryKey = () => [{ url: '/api/me/completed-skills' }] as const

export type GetCompletedSkillsByCoreQueryKey = ReturnType<typeof getCompletedSkillsByCoreQueryKey>

export function getCompletedSkillsByCoreQueryOptions(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = getCompletedSkillsByCoreQueryKey()
	return queryOptions<
		GetCompletedSkillsByCoreQueryResponse,
		ResponseErrorConfig<GetCompletedSkillsByCore401>,
		GetCompletedSkillsByCoreQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return getCompletedSkillsByCore({ ...config, signal: config.signal ?? signal })
		},
	})
}

/**
 * @summary Get completed skills grouped by core for the current user
 * {@link /api/me/completed-skills}
 */
export function useGetCompletedSkillsByCore<
	TData = GetCompletedSkillsByCoreQueryResponse,
	TQueryData = GetCompletedSkillsByCoreQueryResponse,
	TQueryKey extends QueryKey = GetCompletedSkillsByCoreQueryKey,
>(
	options: {
		query?: Partial<
			QueryObserverOptions<
				GetCompletedSkillsByCoreQueryResponse,
				ResponseErrorConfig<GetCompletedSkillsByCore401>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient }
		client?: Partial<RequestConfig> & { client?: Client }
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {}
	const { client: queryClient, ...resolvedOptions } = queryConfig
	const queryKey = resolvedOptions?.queryKey ?? getCompletedSkillsByCoreQueryKey()

	const query = useQuery(
		{
			...getCompletedSkillsByCoreQueryOptions(config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<GetCompletedSkillsByCore401>> & {
		queryKey: TQueryKey
	}

	query.queryKey = queryKey as TQueryKey

	return query
}
