/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type { GetAuthMeQueryResponse, GetAuthMe401 } from '../../types/meController/GetAuthMe'

import { queryOptions, useQuery } from '@tanstack/react-query'

import { getAuthMe } from '../../clients/meController/getAuthMe'

export const getAuthMeQueryKey = () => [{ url: '/api/me' }] as const

export type GetAuthMeQueryKey = ReturnType<typeof getAuthMeQueryKey>

export function getAuthMeQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {
	const queryKey = getAuthMeQueryKey()
	return queryOptions<
		GetAuthMeQueryResponse,
		ResponseErrorConfig<GetAuthMe401>,
		GetAuthMeQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return getAuthMe({ ...config, signal: config.signal ?? signal })
		},
	})
}

/**
 * @summary Get the current user profile
 * {@link /api/me}
 */
export function useGetAuthMe<
	TData = GetAuthMeQueryResponse,
	TQueryData = GetAuthMeQueryResponse,
	TQueryKey extends QueryKey = GetAuthMeQueryKey,
>(
	options: {
		query?: Partial<
			QueryObserverOptions<
				GetAuthMeQueryResponse,
				ResponseErrorConfig<GetAuthMe401>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient }
		client?: Partial<RequestConfig> & { client?: Client }
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {}
	const { client: queryClient, ...resolvedOptions } = queryConfig
	const queryKey = resolvedOptions?.queryKey ?? getAuthMeQueryKey()

	const query = useQuery(
		{
			...getAuthMeQueryOptions(config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<GetAuthMe401>> & { queryKey: TQueryKey }

	query.queryKey = queryKey as TQueryKey

	return query
}
