/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
	QueryKey,
	QueryClient,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type { GetAuthMeQueryResponse, GetAuthMe401 } from '../../types/meController/GetAuthMe'

import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

import { getAuthMe } from '../../clients/meController/getAuthMe'

export const getAuthMeSuspenseQueryKey = () => [{ url: '/api/me' }] as const

export type GetAuthMeSuspenseQueryKey = ReturnType<typeof getAuthMeSuspenseQueryKey>

export function getAuthMeSuspenseQueryOptions(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = getAuthMeSuspenseQueryKey()
	return queryOptions<
		GetAuthMeQueryResponse,
		ResponseErrorConfig<GetAuthMe401>,
		GetAuthMeQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return getAuthMe({ ...config, signal: config.signal ?? signal })
		},
	})
}

/**
 * @summary Get the current user profile
 * {@link /api/me}
 */
export function useGetAuthMeSuspense<
	TData = GetAuthMeQueryResponse,
	TQueryKey extends QueryKey = GetAuthMeSuspenseQueryKey,
>(
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				GetAuthMeQueryResponse,
				ResponseErrorConfig<GetAuthMe401>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient }
		client?: Partial<RequestConfig> & { client?: Client }
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {}
	const { client: queryClient, ...resolvedOptions } = queryConfig
	const queryKey = resolvedOptions?.queryKey ?? getAuthMeSuspenseQueryKey()

	const query = useSuspenseQuery(
		{
			...getAuthMeSuspenseQueryOptions(config),
			...resolvedOptions,
			queryKey,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetAuthMe401>> & { queryKey: TQueryKey }

	query.queryKey = queryKey as TQueryKey

	return query
}
