/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { CoreRow } from '../CoreRow'

export interface GetCoreRowsQueryParams {
	/**
	 * PostgREST filter expression, e.g. "eq.frontend"
	 *
	 * @type string | undefined
	 */
	type?: string
	/**
	 * PostgREST column projection
	 *
	 * @type string | undefined
	 */
	select?: string
	/** @type string | undefined */
	order?: string
	/**
	 * @type integer | undefined
	 * @minLength 0
	 */
	limit?: number
}

/** Success */
export type GetCoreRows200 = CoreRow[]

export type GetCoreRowsQueryResponse = GetCoreRows200

export type GetCoreRowsQuery = {
	Response: GetCoreRows200
	QueryParams: GetCoreRowsQueryParams
	Errors: any
}
