/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

import { skillSchema } from '../skillSchema'

export const getSkillByIdPathParamsSchema = z.object({
	id: z.string(),
})

/** Success */
export const getSkillById200Schema = z.lazy(() => skillSchema)

/** Not found */
export const getSkillById404Schema = z.unknown()

export const getSkillByIdQueryResponseSchema = z.lazy(() => getSkillById200Schema)
