/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

export const getSkillsQueryParamsSchema = z.optional(
	z.object({
		search: z.optional(z.string()),
		topic: z.optional(z.string()),
		difficulty: z.optional(z.enum(['easy', 'medium', 'hard'])),
		minQuestionsCount: z.optional(z.int().check(z.minimum(0))),
		maxQuestionsCount: z.optional(z.int().check(z.minimum(0))),
	}),
)

/** Success */
export const getSkills200Schema = z.array(
	z.object({
		id: z.string(),
		title: z.string(),
		questionsCount: z.int().check(z.minimum(0)),
		difficulty: z.enum(['easy', 'medium', 'hard']),
		topic: z.string(),
	}),
)

export const getSkillsQueryResponseSchema = z.lazy(() => getSkills200Schema)
