/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

import { skillCompletionSchema } from '../skillCompletionSchema'

export const setSkillCompletionPathParamsSchema = z.object({
	id: z.string(),
})

/** Success */
export const setSkillCompletion200Schema = z.lazy(() => skillCompletionSchema)

/** Invalid request body */
export const setSkillCompletion400Schema = z.unknown()

/** Not authenticated */
export const setSkillCompletion401Schema = z.unknown()

/** Skill not found */
export const setSkillCompletion404Schema = z.unknown()

export const setSkillCompletionMutationRequestSchema = z.object({
	completed: z.boolean(),
})

export const setSkillCompletionMutationResponseSchema = z.lazy(() => setSkillCompletion200Schema)
