/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

/** Success */
export interface GetExample200 {
	/** @type string | undefined */
	message?: string
}

/** Not found */
export type GetExample404 = unknown

export type GetExampleQueryResponse = GetExample200

export type GetExampleQuery = {
	Response: GetExample200
	Errors: GetExample404
}
