/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type { GetDashboardStatsQueryResponse } from '../../types/dashboardController/GetDashboardStats'

import { queryOptions, useQuery } from '@tanstack/react-query'

import { getDashboardStats } from '../../clients/dashboardController/getDashboardStats'

export const getDashboardStatsQueryKey = () => [{ url: '/api/dashboard-stats' }] as const

export type GetDashboardStatsQueryKey = ReturnType<typeof getDashboardStatsQueryKey>

export function getDashboardStatsQueryOptions(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = getDashboardStatsQueryKey()
	return queryOptions<
		GetDashboardStatsQueryResponse,
		ResponseErrorConfig<Error>,
		GetDashboardStatsQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return getDashboardStats({ ...config, signal: config.signal ?? signal })
		},
	})
}

/**
 * @summary Get aggregated catalog and personal progress statistics for the home dashboard
 * {@link /api/dashboard-stats}
 */
export function useGetDashboardStats<
	TData = GetDashboardStatsQueryResponse,
	TQueryData = GetDashboardStatsQueryResponse,
	TQueryKey extends QueryKey = GetDashboardStatsQueryKey,
>(
	options: {
		query?: Partial<
			QueryObserverOptions<
				GetDashboardStatsQueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient }
		client?: Partial<RequestConfig> & { client?: Client }
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {}
	const { client: queryClient, ...resolvedOptions } = queryConfig
	const queryKey = resolvedOptions?.queryKey ?? getDashboardStatsQueryKey()

	const query = useQuery(
		{
			...getDashboardStatsQueryOptions(config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

	query.queryKey = queryKey as TQueryKey

	return query
}
