/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
	QueryKey,
	QueryClient,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type { GetDashboardStatsQueryResponse } from '../../types/dashboardController/GetDashboardStats'

import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

import { getDashboardStats } from '../../clients/dashboardController/getDashboardStats'

export const getDashboardStatsSuspenseQueryKey = () => [{ url: '/api/dashboard-stats' }] as const

export type GetDashboardStatsSuspenseQueryKey = ReturnType<typeof getDashboardStatsSuspenseQueryKey>

export function getDashboardStatsSuspenseQueryOptions(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = getDashboardStatsSuspenseQueryKey()
	return queryOptions<
		GetDashboardStatsQueryResponse,
		ResponseErrorConfig<Error>,
		GetDashboardStatsQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return getDashboardStats({ ...config, signal: config.signal ?? signal })
		},
	})
}

/**
 * @summary Get aggregated catalog and personal progress statistics for the home dashboard
 * {@link /api/dashboard-stats}
 */
export function useGetDashboardStatsSuspense<
	TData = GetDashboardStatsQueryResponse,
	TQueryKey extends QueryKey = GetDashboardStatsSuspenseQueryKey,
>(
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				GetDashboardStatsQueryResponse,
				ResponseErrorConfig<Error>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient }
		client?: Partial<RequestConfig> & { client?: Client }
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {}
	const { client: queryClient, ...resolvedOptions } = queryConfig
	const queryKey = resolvedOptions?.queryKey ?? getDashboardStatsSuspenseQueryKey()

	const query = useSuspenseQuery(
		{
			...getDashboardStatsSuspenseQueryOptions(config),
			...resolvedOptions,
			queryKey,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

	query.queryKey = queryKey as TQueryKey

	return query
}
