/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type {
	GetSkillRowsQueryResponse,
	GetSkillRowsQueryParams,
} from '../../types/skillsController/GetSkillRows'

import fetch from '../../../client'
import { getSkillRowsQueryResponseSchema } from '../../zod/skillsController/getSkillRowsSchema'

function getGetSkillRowsUrl() {
	const res = { method: 'GET', url: `/skills` as const }
	return res
}

/**
 * @summary Query the skills table directly via PostgREST
 * {@link /skills}
 */
export async function getSkillRows(
	{ params }: { params?: GetSkillRowsQueryParams } = {},
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config

	const res = await request<GetSkillRowsQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: 'GET',
		url: getGetSkillRowsUrl().url.toString(),
		params,
		...requestConfig,
	})
	return getSkillRowsQueryResponseSchema.parse(res.data)
}
