/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Core } from '../types/Core'

import { faker } from '@faker-js/faker'

export function createCore(data?: Partial<Core>): Core {
	return {
		...{
			type: faker.helpers.arrayElement<NonNullable<Core>['type']>([
				'frontend',
				'backend',
				'devops',
				'design',
			]),
			name: faker.string.alpha({ length: 1 }),
			description: faker.string.alpha({ length: 1 }),
			icon: faker.helpers.arrayElement<NonNullable<Core>['icon']>([
				'code',
				'server',
				'ship',
				'palette',
			]),
			isAvailable: faker.datatype.boolean(),
		},
		...(data || {}),
	}
}
