/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Type } from '../types/Type'

import { faker } from '@faker-js/faker'

export function createType(data?: Partial<Type>): Type {
	return data || faker.helpers.arrayElement<Type>(['frontend', 'backend', 'devops', 'design'])
}
