/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { SkillCompletion } from '../types/SkillCompletion'

import { faker } from '@faker-js/faker'

export function createSkillCompletion(data?: Partial<SkillCompletion>): SkillCompletion {
	return {
		...{
			completed: faker.datatype.boolean(),
			completedSkillsCount: faker.number.int({ min: 0 }),
		},
		...(data || {}),
	}
}
