/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Skill } from '../types/Skill'

import { faker } from '@faker-js/faker'

export function createSkill(data?: Partial<Skill>): Skill {
	return {
		...{
			title: faker.string.alpha(),
			questions: faker.helpers.multiple(() => faker.string.alpha()),
		},
		...(data || {}),
	}
}
