/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { DashboardStats } from '../types/DashboardStats'

import { faker } from '@faker-js/faker'

export function createDashboardStats(data?: Partial<DashboardStats>): DashboardStats {
	return {
		...{
			skillsCount: faker.number.int({ min: 0 }),
			topicsCount: faker.number.int({ min: 0 }),
			questionsCount: faker.number.int({ min: 0 }),
			completedSkillsCount: faker.number.int({ min: 0 }),
		},
		...(data || {}),
	}
}
