/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { AuthMe } from '../types/AuthMe'

import { faker } from '@faker-js/faker'

export function createAuthMe(data?: Partial<AuthMe>): AuthMe {
	return {
		...{
			id: faker.string.alpha(),
			name: faker.string.alpha({ length: 3 }),
			email: faker.internet.email(),
			gender: faker.helpers.arrayElement<NonNullable<AuthMe>['gender']>([
				'male',
				'female',
				'other',
			]),
			age: faker.number.int({ min: 1, max: 120 }),
			image: faker.internet.url(),
		},
		...(data || {}),
	}
}
