/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
	QueryKey,
	QueryClient,
	QueryObserverOptions,
	UseQueryResult,
} from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type {
	GetExampleQueryResponse,
	GetExample404,
} from '../../types/exampleController/GetExample'

import { queryOptions, useQuery } from '@tanstack/react-query'

import { getExample } from '../../clients/exampleController/getExample'

export const getExampleQueryKey = () => [{ url: '/api/example' }] as const

export type GetExampleQueryKey = ReturnType<typeof getExampleQueryKey>

export function getExampleQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {
	const queryKey = getExampleQueryKey()
	return queryOptions<
		GetExampleQueryResponse,
		ResponseErrorConfig<GetExample404>,
		GetExampleQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return getExample({ ...config, signal: config.signal ?? signal })
		},
	})
}

/**
 * @summary Example endpoint
 * {@link /api/example}
 */
export function useGetExample<
	TData = GetExampleQueryResponse,
	TQueryData = GetExampleQueryResponse,
	TQueryKey extends QueryKey = GetExampleQueryKey,
>(
	options: {
		query?: Partial<
			QueryObserverOptions<
				GetExampleQueryResponse,
				ResponseErrorConfig<GetExample404>,
				TData,
				TQueryData,
				TQueryKey
			>
		> & { client?: QueryClient }
		client?: Partial<RequestConfig> & { client?: Client }
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {}
	const { client: queryClient, ...resolvedOptions } = queryConfig
	const queryKey = resolvedOptions?.queryKey ?? getExampleQueryKey()

	const query = useQuery(
		{
			...getExampleQueryOptions(config),
			...resolvedOptions,
			queryKey,
		} as unknown as QueryObserverOptions,
		queryClient,
	) as UseQueryResult<TData, ResponseErrorConfig<GetExample404>> & { queryKey: TQueryKey }

	query.queryKey = queryKey as TQueryKey

	return query
}
