/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
	QueryKey,
	QueryClient,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from '@tanstack/react-query'

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type {
	GetExampleQueryResponse,
	GetExample404,
} from '../../types/exampleController/GetExample'

import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

import { getExample } from '../../clients/exampleController/getExample'

export const getExampleSuspenseQueryKey = () => [{ url: '/api/example' }] as const

export type GetExampleSuspenseQueryKey = ReturnType<typeof getExampleSuspenseQueryKey>

export function getExampleSuspenseQueryOptions(
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const queryKey = getExampleSuspenseQueryKey()
	return queryOptions<
		GetExampleQueryResponse,
		ResponseErrorConfig<GetExample404>,
		GetExampleQueryResponse,
		typeof queryKey
	>({
		queryKey,
		queryFn: async ({ signal }) => {
			return getExample({ ...config, signal: config.signal ?? signal })
		},
	})
}

/**
 * @summary Example endpoint
 * {@link /api/example}
 */
export function useGetExampleSuspense<
	TData = GetExampleQueryResponse,
	TQueryKey extends QueryKey = GetExampleSuspenseQueryKey,
>(
	options: {
		query?: Partial<
			UseSuspenseQueryOptions<
				GetExampleQueryResponse,
				ResponseErrorConfig<GetExample404>,
				TData,
				TQueryKey
			>
		> & { client?: QueryClient }
		client?: Partial<RequestConfig> & { client?: Client }
	} = {},
) {
	const { query: queryConfig = {}, client: config = {} } = options ?? {}
	const { client: queryClient, ...resolvedOptions } = queryConfig
	const queryKey = resolvedOptions?.queryKey ?? getExampleSuspenseQueryKey()

	const query = useSuspenseQuery(
		{
			...getExampleSuspenseQueryOptions(config),
			...resolvedOptions,
			queryKey,
		} as unknown as UseSuspenseQueryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetExample404>> & { queryKey: TQueryKey }

	query.queryKey = queryKey as TQueryKey

	return query
}
