/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { GetCores200, GetCoresQueryResponse } from '../../types/coresController/GetCores'

import { faker } from '@faker-js/faker'

import { createCore } from '../createCore'

/** Success */
export function createGetCores200(data?: GetCores200): GetCores200 {
	return [...faker.helpers.multiple(() => createCore()), ...(data || [])]
}

export function createGetCoresQueryResponse(
	data?: Partial<GetCoresQueryResponse>,
): GetCoresQueryResponse {
	return data || faker.helpers.arrayElement<any>([createGetCores200()])
}
