/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type {
	GetCoreRowsQueryResponse,
	GetCoreRowsQueryParams,
} from '../../types/coresController/GetCoreRows'

import fetch from '../../../client'
import { getCoreRowsQueryResponseSchema } from '../../zod/coresController/getCoreRowsSchema'

function getGetCoreRowsUrl() {
	const res = { method: 'GET', url: `/cores` as const }
	return res
}

/**
 * @summary Query the cores table directly via PostgREST
 * {@link /cores}
 */
export async function getCoreRows(
	{ params }: { params?: GetCoreRowsQueryParams } = {},
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config

	const res = await request<GetCoreRowsQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: 'GET',
		url: getGetCoreRowsUrl().url.toString(),
		params,
		...requestConfig,
	})
	return getCoreRowsQueryResponseSchema.parse(res.data)
}
