/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
	GetExample200,
	GetExampleQueryResponse,
} from '../../types/exampleController/GetExample'

import { faker } from '@faker-js/faker'

/** Success */
export function createGetExample200(data?: Partial<GetExample200>): GetExample200 {
	return {
		...{ message: faker.string.alpha() },
		...(data || {}),
	}
}

/** Not found */
export function createGetExample404() {
	return undefined
}

export function createGetExampleQueryResponse(
	data?: Partial<GetExampleQueryResponse>,
): GetExampleQueryResponse {
	return data || faker.helpers.arrayElement<any>([createGetExample200()])
}
