/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type { GetCoresQueryResponse } from '../../types/coresController/GetCores'

import fetch from '../../../client'
import { getCoresQueryResponseSchema } from '../../zod/coresController/getCoresSchema'

function getGetCoresUrl() {
	const res = { method: 'GET', url: `/api/cores` as const }
	return res
}

/**
 * @summary List catalog cores
 * {@link /api/cores}
 */
export async function getCores(config: Partial<RequestConfig> & { client?: Client } = {}) {
	const { client: request = fetch, ...requestConfig } = config

	const res = await request<GetCoresQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: 'GET',
		url: getGetCoresUrl().url.toString(),
		...requestConfig,
	})
	return getCoresQueryResponseSchema.parse(res.data)
}
