/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { AuthMe } from '../AuthMe'

/** Success */
export type GetAuthMe200 = AuthMe

/** Not authenticated */
export type GetAuthMe401 = unknown

export type GetAuthMeQueryResponse = GetAuthMe200

export type GetAuthMeQuery = {
	Response: GetAuthMe200
	Errors: GetAuthMe401
}
