/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Type } from '../Type'

/** Success */
export type GetCompletedSkillsByCore200 = {
	/** @type string */
	core: Type
	/** @type string */
	coreName: string
	/** @type array */
	skills: {
		/** @type string */
		id: string
		/** @type string */
		title: string
	}[]
}[]

/** Not authenticated */
export type GetCompletedSkillsByCore401 = unknown

export type GetCompletedSkillsByCoreQueryResponse = GetCompletedSkillsByCore200

export type GetCompletedSkillsByCoreQuery = {
	Response: GetCompletedSkillsByCore200
	Errors: GetCompletedSkillsByCore401
}
