/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

export interface AuthMe {
	/** @type string */
	id: string
	/**
	 * @type string
	 * @minLength 3
	 */
	name: string
	/** @type string, email */
	email: string
	/** @type string */
	gender: 'male' | 'female' | 'other'
	/**
	 * @type integer
	 * @minLength 1
	 * @maxLength 120
	 */
	age: number
	/** @type string | undefined, uri */
	image?: string
}
