/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

export interface Core {
	/** @type string */
	type: 'frontend' | 'backend' | 'devops' | 'design'
	/**
	 * @type string
	 * @minLength 1
	 */
	name: string
	/**
	 * @type string
	 * @minLength 1
	 */
	description: string
	/** @type string */
	icon: 'code' | 'server' | 'ship' | 'palette'
	/** @type boolean */
	isAvailable: boolean
}
