/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

export interface DashboardStats {
	/**
	 * @type integer
	 * @minLength 0
	 */
	skillsCount: number
	/**
	 * @type integer
	 * @minLength 0
	 */
	topicsCount: number
	/**
	 * @type integer
	 * @minLength 0
	 */
	questionsCount: number
	/**
	 * Present only when the request is made by an authenticated user.
	 *
	 * @type integer | undefined
	 * @minLength 0
	 */
	completedSkillsCount?: number
}
