/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

export interface SkillCompletion {
	/**
	 * Resulting completion mark of the current user for the requested skill.
	 *
	 * @type boolean
	 */
	completed: boolean
	/**
	 * Total number of skills the current user has marked as completed.
	 *
	 * @type integer
	 * @minLength 0
	 */
	completedSkillsCount: number
}
