/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

export interface Skill {
	/** @type string */
	title: string
	/** @type array */
	questions: string[]
	/** @type string */
	core: 'frontend' | 'backend' | 'devops' | 'design'
}
