/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

export interface Skill {
	/** @type string */
	title: string
	/** @type array */
	questions: string[]
	/**
	 * Completion mark of the current user. Present only when the request is made by an
	 * authenticated user.
	 *
	 * @type boolean | undefined
	 */
	completed?: boolean
	/** @type string */
	core: 'frontend' | 'backend' | 'devops' | 'design'
}
