/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

import { skillRowSchema } from '../skillRowSchema'

export const getSkillRowsQueryParamsSchema = z.optional(
	z.object({
		id: z.optional(z.string()),
		title: z.optional(z.string()),
		topic: z.optional(z.string()),
		difficulty: z.optional(z.string()),
		questions_count: z.optional(z.array(z.string())),
		select: z.optional(z.string()),
		order: z.optional(z.string()),
		limit: z.optional(z.int().check(z.minimum(0))),
	}),
)

/** Success */
export const getSkillRows200Schema = z.array(z.lazy(() => skillRowSchema))

export const getSkillRowsQueryResponseSchema = z.lazy(() => getSkillRows200Schema)
