/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Core } from '../Core'

/** Success */
export type GetCores200 = Core[]

export type GetCoresQueryResponse = GetCores200

export type GetCoresQuery = {
	Response: GetCores200
	Errors: any
}
