/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Skill } from '../Skill'

export interface GetSkillByIdPathParams {
	/** @type string */
	id: string
}

/** Success */
export type GetSkillById200 = Skill

/** Not found */
export type GetSkillById404 = unknown

export type GetSkillByIdQueryResponse = GetSkillById200

export type GetSkillByIdQuery = {
	Response: GetSkillById200
	PathParams: GetSkillByIdPathParams
	Errors: GetSkillById404
}
