/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

export interface GetSkillsQueryParams {
	/** @type string | undefined */
	search?: string
	/** @type string | undefined */
	topic?: string
	/** @type string | undefined */
	difficulty?: 'easy' | 'medium' | 'hard'
	/**
	 * @type integer | undefined
	 * @minLength 0
	 */
	minQuestionsCount?: number
	/**
	 * @type integer | undefined
	 * @minLength 0
	 */
	maxQuestionsCount?: number
}

/** Success */
export type GetSkills200 = {
	/** @type string */
	id: string
	/** @type string */
	title: string
	/**
	 * @type integer
	 * @minLength 0
	 */
	questionsCount: number
	/** @type string */
	difficulty: 'easy' | 'medium' | 'hard'
	/** @type string */
	topic: string
}[]

export type GetSkillsQueryResponse = GetSkills200

export type GetSkillsQuery = {
	Response: GetSkills200
	QueryParams: GetSkillsQueryParams
	Errors: any
}
