/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { SkillCompletion } from '../SkillCompletion'

export interface SetSkillCompletionPathParams {
	/** @type string */
	id: string
}

/** Success */
export type SetSkillCompletion200 = SkillCompletion

/** Invalid request body */
export type SetSkillCompletion400 = unknown

/** Not authenticated */
export type SetSkillCompletion401 = unknown

/** Skill not found */
export type SetSkillCompletion404 = unknown

export interface SetSkillCompletionMutationRequest {
	/**
	 * Target completion mark. The operation is idempotent.
	 *
	 * @type boolean
	 */
	completed: boolean
}

export type SetSkillCompletionMutationResponse = SetSkillCompletion200

export type SetSkillCompletionMutation = {
	Response: SetSkillCompletion200
	Request: SetSkillCompletionMutationRequest
	PathParams: SetSkillCompletionPathParams
	Errors: SetSkillCompletion400 | SetSkillCompletion401 | SetSkillCompletion404
}
