/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type {
	GetSkillByIdQueryResponse,
	GetSkillByIdPathParams,
	GetSkillById404,
} from '../../types/skillsController/GetSkillById'

import fetch from '../../../client'
import { getSkillByIdQueryResponseSchema } from '../../zod/skillsController/getSkillByIdSchema'

function getGetSkillByIdUrl({ id }: { id: GetSkillByIdPathParams['id'] }) {
	const res = { method: 'GET', url: `/api/skills/${id}` as const }
	return res
}

/**
 * @summary Get skill by id
 * {@link /api/skills/:id}
 */
export async function getSkillById(
	{ id }: { id: GetSkillByIdPathParams['id'] },
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config

	const res = await request<
		GetSkillByIdQueryResponse,
		ResponseErrorConfig<GetSkillById404>,
		unknown
	>({ method: 'GET', url: getGetSkillByIdUrl({ id }).url.toString(), ...requestConfig })
	return getSkillByIdQueryResponseSchema.parse(res.data)
}
