/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type {
	GetSkillsQueryResponse,
	GetSkillsQueryParams,
} from '../../types/skillsController/GetSkills'

import fetch from '../../../client'
import { getSkillsQueryResponseSchema } from '../../zod/skillsController/getSkillsSchema'

function getGetSkillsUrl() {
	const res = { method: 'GET', url: `/api/skills` as const }
	return res
}

/**
 * @summary List skill cards
 * {@link /api/skills}
 */
export async function getSkills(
	{ params }: { params?: GetSkillsQueryParams } = {},
	config: Partial<RequestConfig> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config

	const res = await request<GetSkillsQueryResponse, ResponseErrorConfig<Error>, unknown>({
		method: 'GET',
		url: getGetSkillsUrl().url.toString(),
		params,
		...requestConfig,
	})
	return getSkillsQueryResponseSchema.parse(res.data)
}
