/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { Client, RequestConfig, ResponseErrorConfig } from '../../../client'
import type {
	SetSkillCompletionMutationRequest,
	SetSkillCompletionMutationResponse,
	SetSkillCompletionPathParams,
	SetSkillCompletion400,
	SetSkillCompletion401,
	SetSkillCompletion404,
} from '../../types/skillsController/SetSkillCompletion'

import fetch from '../../../client'
import {
	setSkillCompletionMutationResponseSchema,
	setSkillCompletionMutationRequestSchema,
} from '../../zod/skillsController/setSkillCompletionSchema'

function getSetSkillCompletionUrl({ id }: { id: SetSkillCompletionPathParams['id'] }) {
	const res = { method: 'PUT', url: `/api/skills/${id}/completion` as const }
	return res
}

/**
 * @summary Set skill completion for the current user
 * {@link /api/skills/:id/completion}
 */
export async function setSkillCompletion(
	{
		id,
		data,
	}: { id: SetSkillCompletionPathParams['id']; data: SetSkillCompletionMutationRequest },
	config: Partial<RequestConfig<SetSkillCompletionMutationRequest>> & { client?: Client } = {},
) {
	const { client: request = fetch, ...requestConfig } = config

	const requestData = setSkillCompletionMutationRequestSchema.parse(data)

	const res = await request<
		SetSkillCompletionMutationResponse,
		ResponseErrorConfig<SetSkillCompletion400 | SetSkillCompletion401 | SetSkillCompletion404>,
		SetSkillCompletionMutationRequest
	>({
		method: 'PUT',
		url: getSetSkillCompletionUrl({ id }).url.toString(),
		data: requestData,
		...requestConfig,
	})
	return setSkillCompletionMutationResponseSchema.parse(res.data)
}
