/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { DashboardStats } from '../DashboardStats'

/** Success */
export type GetDashboardStats200 = DashboardStats

export type GetDashboardStatsQueryResponse = GetDashboardStats200

export type GetDashboardStatsQuery = {
	Response: GetDashboardStats200
	Errors: any
}
