/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import * as z from 'zod/mini'

import { coreSchema } from '../coreSchema'

/** Success */
export const getCores200Schema = z.array(z.lazy(() => coreSchema))

export const getCoresQueryResponseSchema = z.lazy(() => getCores200Schema)
