/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type { MockRoute } from '../mock-client'

import { createGetExampleQueryResponse } from './mocks/exampleController/createGetExample'

export const mockRoutes = [
	{ method: 'GET', pattern: /^\/api\/example$/, create: createGetExampleQueryResponse },
] as MockRoute[]
