/** Generated by Kubb (https://kubb.dev/). Do not edit manually. */

import type {
	GetDashboardStats200,
	GetDashboardStatsQueryResponse,
} from '../../types/dashboardController/GetDashboardStats'

import { faker } from '@faker-js/faker'

import { createDashboardStats } from '../createDashboardStats'

/** Success */
export function createGetDashboardStats200(
	data?: Partial<GetDashboardStats200>,
): GetDashboardStats200 {
	return createDashboardStats(data)
}

export function createGetDashboardStatsQueryResponse(
	data?: Partial<GetDashboardStatsQueryResponse>,
): GetDashboardStatsQueryResponse {
	return data || faker.helpers.arrayElement<any>([createGetDashboardStats200()])
}
